### ISSUE TITLE
I'm sorry

### ISSUE THREAD

**Issue by ejiektpobehuk** [djmattyg007/SteamFastLogin#1]
I do know it's not a right place to ask you to fix your [aur package](https://aur.archlinux.org/packages/python-urwidtrees/) but you've been ignoring me everywhere else.

**Comment by djmattyg007** [comment]
I'm terribly sorry for not attending to this sooner. I'm not sure how it slipped past my attention. Please accept my greatest apologies.

I will update the PKGBUILD accordingly within the next few hours, but I will also be disowning the package on the AUR, as I no longer use thr library. I strongly encourage you to take up ownership of the package.
