### ISSUE TITLE
Not Working After Steam Updated Steam

### ISSUE THREAD

**Issue by ghost** [djmattyg007/SteamFastLogin#3]
It was working perfectly until Steam decided to update their login on Steam. Now on Steam there is a new GUI, so I suppose that they changed something in their code. That's why SteamFastLogin doesn't work anymore. It's only my guess, but still it doesn't remember my credentials.

**Comment by djmattyg007** [comment]
Hi @niereklamuj Thanks for letting me know about this. I noticed there was another update to Steam a short time ago, where they claim to have fixed an issue that seems related to this. Would you be able to make sure you're running the very latest version and then try again? You might have to wait a little bit for the update to roll out.

**Comment by ghost** [comment]
It's working. What I had to do was to relogin on my all accounts, and now it's working with every account. Maybe it was a fluke from the Steam side. That's why I needed to relogin, because they changed something.

**Comment by djmattyg007** [comment]
Thanks for confirming. I’ll close this issue now.
